---
title: "test1"
output: html_document
date: "2023-05-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Paths
```{r}
datapath = "data/"
```


## load Packages
```{r, cache=FALSE}
library(data.table)
library(lubridate)
library(tidyverse)
library(kableExtra)

#library(fable) #also  has a forecast and accuracy method!!
```

## Functions
```{r}
scale2 <- function(x, na.rm = TRUE) (x - mean(x, na.rm = na.rm)) / sd(x, na.rm)

lag_trends = function(lags, input_ds, col_pos){
  
  out = list()
  for(i in seq_along(col_pos)){
    col_sel = col_pos[i]
    t_out = list()
    for(j in seq_along(lags)){
      t_out[[j]] = dplyr::lag(input_ds[,col_sel],lags[j])
    }
    out[[i]] = do.call(cbind,t_out)
    if(ncol(out[[i]]) > 1){
      colnames(out[[i]]) = paste0(colnames(input_ds)[col_sel], "_lag", lags) 
    }
  }
  res = do.call(cbind,out)
  return(res)
}

lag_trends_ts = function(lags, input_ts, col_pos){
  stopifnot(is.ts(input_ts))
  
  out = list()
  lags_neg = -1*lags
  
  for(i in seq_along(col_pos)){
    col_sel = col_pos[i]
    t_out = list()
    for(j in seq_along(lags)){
      t_out[[j]] = stats::lag(input_ts[,col_sel],lags_neg[j])
    }
    out[[i]] = do.call(cbind,t_out)
    if(ncol(out[[i]]) > 1){
      colnames(out[[i]]) = paste0(colnames(input_ts)[col_sel], "_lag", lags) 
    }
    out[[i]] = fable::as_tsibble(out[[i]]) #need this for binding the data accurately
  }
  res = as.ts(do.call(bind_rows,out))
  return(res)
}
```


## Volatility Index {-}
```{r}

vol_ind = read_delim(paste0(datapath,"country_volatility_index.csv")) %>%
  mutate(geo = str_split(Countries, " ", simplify = T)[,1], .before = 1,
         country = str_remove(Countries, ".*\\("), 
         country = str_extract(country, ".*(?=\\))"))

country_code_list = unlist(vol_ind$geo)
country_list = unlist(vol_ind$country)
country_code_list[country_list=="Greece"] <- "GR"
```

```{r}
addMissings = tibble(country_code = c("AT","GR","GR"),
        date = as_date(c("2008-10-01","1995-02-01", "1997-12-01")),
        resid_total = c(NA,NA,NA))
```

## R Markdown

```{r, results='asis'}
ind_path = paste0(datapath,"indicators/")

fl = list.files(ind_path)
ind_df = list()

for(i in 1:length(fl)){
  ind_in = fread(paste0(ind_path, fl[i]))
  monat = lubridate::my(substr(fl[i], 25,31))
  
  ind_df[[i]] = ind_in[,-c(1:3)] %>% 
    as_tibble() %>%
    mutate(country_code = case_when(
      geo == "EL" ~ "GR",
      TRUE ~ geo
    )) %>%
    mutate(date = as_date(paste0(TIME_PERIOD,"-01")),.before=1) %>%
    filter(country_code %in% country_code_list & nace_r2 == "I551-I553" & unit=="NR" & c_resid == "TOTAL") %>%
    rename(resid_total = OBS_VALUE) %>%
    select(country_code, date, resid_total) %>%
    add_row(addMissings) %>%
    arrange(country_code, date) %>%
    filter(country_code == "FR" & date >= as_date("2010-01-01") | 
             country_code == "CY" & date >= as_date("2000-01-01") | 
             country_code == "DK" & date >= as_date("2007-01-01") | 
             country_code == "MT" & date >= as_date("2010-01-01") |
             !country_code %in% c("FR","CY","DK","MT")) %>%
    group_by(country_code) %>%
    mutate(resid_total= zoo::na.locf(resid_total, na.rm = FALSE)) %>%
    mutate(resid_total_sqrt = sqrt(resid_total),
           resid_total_log = log(resid_total),
           resid_total_std = scale2(resid_total),
           mean = mean(resid_total),
           sd = sd(resid_total)) %>%
    ungroup() %>%
    arrange(country_code,date) %>%
    add_column(monat)
}


df1 = ind_df %>%
  reduce(bind_rows)


df1 %>%
  group_by(country_code, monat) %>%
  summarise(obs = n()) %>%
  kable() %>%
  kable_styling()

```

## Summary
```{r}
df1 %>%
  group_by(country_code, monat) %>%
  summarise(obs = n()) %>%
  ungroup() %>%
  group_by(monat, obs) %>%
  mutate(cl = paste(country_code, collapse = ", ")) %>%
  ungroup() %>%
  select(!country_code) %>%
  distinct() %>%
  arrange(cl, monat) %>%
  kable() %>%
  kable_styling()
```

## Trends
```{r}
trends100 = read_csv(paste0(datapath, "trends_100.csv"))
trends100 %>%
  group_by(country_code) %>%
  summarise(n=n()) %>%
  kable() %>%
  kable_styling()
```

